# ML : Tutoriel sur Numpy

In [1]:
import numpy as np

## 1. Création

In [2]:
# Créer une matrice numpy à partir d'une liste Python
# le type des éléments doit être homogène
A = np.array([[1, 2, 3], [4, 5, 6]])

A

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# Créer une matrice identité : des 1 au diagonal et des 0 partout
I = np.eye(5)

I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
# créer une matrice diagonale à partir du premier élément
I2 = np.eye(5, 3)

I2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# Créer un vecteur de 5 éléments dont les valeurs sont des 1
O = np.ones(5)

O

array([1., 1., 1., 1., 1.])

In [6]:
# Créer une matrice de 3X5 éléments dont les valeurs sont des 1
O2 = np.ones((3, 5))

O2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# Créer une matrice de 3X5 éléments dont les valeurs sont des 0
Z = np.zeros((3, 5))

Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
# Créer une matrice de 3X5 éléments dont les valeurs sont des 2.2 (une valeur donnée)
V = np.full((3, 5), 2.2)

V

array([[2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2]])

In [9]:
# Créer un vecteur avec des valeurs dans [0, 5[ (pas = 1)
C = np.arange(0, 5)

C

array([0, 1, 2, 3, 4])

In [10]:
# Créer un vecteur avec des valeurs dans [0, 5[ (pas = 0.5)
P = np.arange(0, 5, 0.5)

P

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [11]:
# Créer une matrice 3X5 avec des valeurs aléatoires dans [0, 1]
A  = np.random.rand(3, 5)

A

array([[0.77980909, 0.51510717, 0.71080604, 0.52292232, 0.65899282],
       [0.37957472, 0.87642282, 0.4274657 , 0.31823589, 0.7653407 ],
       [0.79158987, 0.79187292, 0.62662786, 0.84249114, 0.57402291]])

In [12]:
# Créer un vecteur avec 11 éléments dont les valeurs sont dans [0, 5] 
# c'est comme np.arange(0, 5.000000000001, (5-0+1)/11) 
# j'ai utilisé 5.000000001 pour inclure 5 dans le vecteur
B = np.linspace(0, 5, 11)

B

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [13]:
# Créer une matrice diagonale avec un vecteur donnée
D = np.diag([5, 2, 3, 5])

D

array([[5, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 5]])

In [14]:
# Créer une matrice diagonale avec un vecteur donnée et un décalage (shift)
D1 = np.diag([5, 2, 3, 5], 1)

D1

array([[0, 5, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0]])

In [15]:
# Créer une matrice de vandermonde à partir d'un vecteur T
# Le vecteur sera considéré comme une colonne 
# La dernière colonne c'est T^0, l'avant dernière c'est T^1 et avant c'est T^2, etc.
V = np.vander([2, 3, 5], 3)
V

array([[ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [16]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Lorsqu'on référence une partie d'une matrice, en réalité nous n'avons pas créé une nouvelle matrice
# C'est juste une référence vers une partie de la matrice originale
# Afin de créer une nouvelle matrice, on utilise la méthode copy()
B = A[:, :-1].copy()

B

array([[1, 2],
       [4, 5]])

## 2. Transformation

In [17]:
# On va utiliser deux matrices pour les transformations qui viennent
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8, 9],
    [10, 11, 11]
])

A, B

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 11]]))

In [18]:
# Concaténer les deux matrices sur l'axe 0 (les lignes)
# Dans ce cas, le nombre des colonnes des deux matrice doit être identique
ABv = np.concatenate((A, B), axis=0)

ABv

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 11]])

In [19]:
# Concaténer les deux matrices sur l'axe 1 (les colonnes)
# Dans ce cas, le nombre des lignes des deux matrice doit être identique
ABh = np.concatenate((A, B), axis=1)

ABh

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 11]])

## 3. Indexation

In [20]:
A = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 0]
])

A

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [21]:
# Récupérer la forme de la matrice : les dimensions et le nombre des éléments
# La forme est un tuple dans Python
# Le nombre des éléments dans le tuple indique le nombre des dimensions
# Cette matrice a deux dimensions : la première avec 2 éléments et la deuxième avec 5
A.shape

(2, 5)

In [22]:
# Prenons un exemple d'une matrice avec  3 dimensions
A3 = np.array([
    [[1, 2, 5, 5], [3, 4, 5, 5]],
    [[6, 7, 7, 8], [8, 9, 8, 5]],
    [[6, 7, 7, 8], [8, 9, 8, 5]]
])

A3

array([[[1, 2, 5, 5],
        [3, 4, 5, 5]],

       [[6, 7, 7, 8],
        [8, 9, 8, 5]],

       [[6, 7, 7, 8],
        [8, 9, 8, 5]]])

In [23]:
# La dimension est 3X2X4
A3.shape

(3, 2, 4)

In [24]:
# Récupérer le nombre des éléments dans la troisième dimension
A3.shape[2]

4

In [25]:
A

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [26]:
# toutes les lignes, les colonnes à partir de la deuxième
A[:, 1:]

array([[2, 3, 4, 5],
       [7, 8, 9, 0]])

In [27]:
# toutes les lignes, les colonnes sauf la dernière
A[:, :-1]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [28]:
# toutes les lignes, les colonnes sauf la première
A[:, -1:]

array([[5],
       [0]])

In [29]:
# toutes les lignes, les colonnes sauf les deux premières
A[:, -2:]

array([[4, 5],
       [9, 0]])

In [30]:
# Récupérer les éléments en utilisant un masque 
# Ici, on veut garder toutes les lignes
# Pour les colonnes, on ne veut garder que la première et la troisième
mask = [True, False, True, False, False]

A[:, mask]

array([[1, 3],
       [6, 8]])

In [31]:
# La même chose qu'avant mais en indiquant l'indexe de la colonne à garder
idx = [0, 2]

A[:, idx]

array([[1, 3],
       [6, 8]])

In [32]:
A.shape

(2, 5)

In [33]:
# Ajouter une autre dimension à une matrice
B = A[:, np.newaxis, :]

B

array([[[1, 2, 3, 4, 5]],

       [[6, 7, 8, 9, 0]]])

In [34]:
B.shape

(2, 1, 5)

In [35]:
A = np.array([
    [2, 5, 6, 8, 4],
    [1, 2, 7, 9, 2],
    [2, 3, 7, 8, 9]
])

# Ordonner les lignes (axis=0) d'une matrice selon la première colonne (si égalité, selon la deuxième, etc.)
np.sort(A, axis=0)

array([[1, 2, 6, 8, 2],
       [2, 3, 7, 8, 4],
       [2, 5, 7, 9, 9]])

## 4. Recherche

In [36]:
A

array([[2, 5, 6, 8, 4],
       [1, 2, 7, 9, 2],
       [2, 3, 7, 8, 9]])

In [37]:
# Trouver l'indice de l'élément max dans les lignes
# ça va retourner un vecteur d'une taille égale au nombre des colonnes
# chaque élément représente l'indice de la ligne contenant la valeur max
np.argmax(A, axis=0)

array([0, 0, 1, 1, 2])

In [38]:
# Même chose, mais pour les colonnes
np.argmax(A, axis=1)

array([3, 3, 4])

In [39]:
# Retourne l'indice de l'élément max en considérant la matrice comme étant un vecteur
np.argmax(A)

8

In [40]:
# Retourner les indices des éléments qui satisfont une condition donnée
np.argwhere(A > 5)

array([[0, 2],
       [0, 3],
       [1, 2],
       [1, 3],
       [2, 2],
       [2, 3],
       [2, 4]])

## 5. Opérations

In [41]:
A

array([[2, 5, 6, 8, 4],
       [1, 2, 7, 9, 2],
       [2, 3, 7, 8, 9]])

In [42]:
# Transposé d'une matrice
A.T

array([[2, 1, 2],
       [5, 2, 3],
       [6, 7, 7],
       [8, 9, 8],
       [4, 2, 9]])

In [43]:
# L'exposant d'une matrice : élément par élément (element-wise)
A**2

array([[ 4, 25, 36, 64, 16],
       [ 1,  4, 49, 81,  4],
       [ 4,  9, 49, 64, 81]])

In [44]:
# Somme de deux matrice : élément par élément
# Les deux matrices doivent avoir la même taille
A + A

array([[ 4, 10, 12, 16,  8],
       [ 2,  4, 14, 18,  4],
       [ 4,  6, 14, 16, 18]])

In [45]:
# Multiplication d'un scalaire par une matrice :
# Chaque élément de la matrice sera multiplié par cet élément
2 * A

array([[ 4, 10, 12, 16,  8],
       [ 2,  4, 14, 18,  4],
       [ 4,  6, 14, 16, 18]])

In [46]:
# Multiplication matricielle entre deux matrice : 
# le nombre des colonnes de la première doit être identique au nombre des lignes de la deuxième
B = np.array([
    [5, 2],
    [2, 3],
    [1, 4], 
    [2, 2],
    [3, 1]
])
A @ B

array([[54, 63],
       [40, 56],
       [66, 66]])

## 6. Fonctions mathématiques

In [47]:
A

array([[2, 5, 6, 8, 4],
       [1, 2, 7, 9, 2],
       [2, 3, 7, 8, 9]])

In [48]:
# expronentiel
np.exp(A)

array([[7.38905610e+00, 1.48413159e+02, 4.03428793e+02, 2.98095799e+03,
        5.45981500e+01],
       [2.71828183e+00, 7.38905610e+00, 1.09663316e+03, 8.10308393e+03,
        7.38905610e+00],
       [7.38905610e+00, 2.00855369e+01, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [49]:
# Logarithme
np.log(A)

array([[0.69314718, 1.60943791, 1.79175947, 2.07944154, 1.38629436],
       [0.        , 0.69314718, 1.94591015, 2.19722458, 0.69314718],
       [0.69314718, 1.09861229, 1.94591015, 2.07944154, 2.19722458]])

In [50]:
# Logarithme base 2
np.log2(A)

array([[1.        , 2.32192809, 2.5849625 , 3.        , 2.        ],
       [0.        , 1.        , 2.80735492, 3.169925  , 1.        ],
       [1.        , 1.5849625 , 2.80735492, 3.        , 3.169925  ]])

In [51]:
# Logarithme base 10

np.log10(A)

array([[0.30103   , 0.69897   , 0.77815125, 0.90308999, 0.60205999],
       [0.        , 0.30103   , 0.84509804, 0.95424251, 0.30103   ],
       [0.30103   , 0.47712125, 0.84509804, 0.90308999, 0.95424251]])

In [52]:
# Racine
np.sqrt(A)

array([[1.41421356, 2.23606798, 2.44948974, 2.82842712, 2.        ],
       [1.        , 1.41421356, 2.64575131, 3.        , 1.41421356],
       [1.41421356, 1.73205081, 2.64575131, 2.82842712, 3.        ]])

In [53]:
A

array([[2, 5, 6, 8, 4],
       [1, 2, 7, 9, 2],
       [2, 3, 7, 8, 9]])

In [54]:
# Somme de tous les éléments d'une matrice
A.sum()

75

In [55]:
# Somme de tous les ligne d'une matrice
# Donne un vecteur de taille égale au nombre des colonnes
A.sum(axis=0)

array([ 5, 10, 20, 25, 15])

In [56]:
# Somme de tous les colonnes d'une matrice
# Donne un vecteur de taille égale au nombre des lignes
A.sum(axis=1)

array([25, 21, 29])

In [57]:
# Moyenne de tous les ligne d'une matrice
# Donne un vecteur de taille égale au nombre des colonnes
A.mean(axis=0)

array([1.66666667, 3.33333333, 6.66666667, 8.33333333, 5.        ])

In [58]:
# Ecart-type de tous les ligne d'une matrice
# Donne un vecteur de taille égale au nombre des colonnes
A.std(axis=0)

array([0.47140452, 1.24721913, 0.47140452, 0.47140452, 2.94392029])

In [59]:
# Max de tous les ligne d'une matrice
# Donne un vecteur de taille égale au nombre des colonnes
A.max(axis=0)

array([2, 5, 7, 9, 9])

In [60]:
V = np.array([5, 2, 5, 3, 5, 2, 2])

# Récupérer les éléments sans redoublants
np.unique(V)

array([2, 3, 5])

## 7. Fonctions logiques

In [61]:
A

array([[2, 5, 6, 8, 4],
       [1, 2, 7, 9, 2],
       [2, 3, 7, 8, 9]])

In [62]:
# Appliquer une opération logique afin de tester les éléments d'une matrice
B = A > 5

B

array([[False, False,  True,  True, False],
       [False, False,  True,  True, False],
       [False, False,  True,  True,  True]])

In [63]:
# Convertir les éléments booléens vers des entiers
B.astype(int)

array([[0, 0, 1, 1, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1]])

In [64]:
AA = np.array([False, True, False, True])

BB = np.array([False, False, True, True])

In [65]:
# Et logique
AA & BB

array([False, False, False,  True])

In [66]:
# Ou logique
AA | BB

array([False,  True,  True,  True])

In [67]:
# Non logique
np.logical_not(AA)

array([ True, False,  True, False])