# Lab : Outils (Numpy)

In [1]:
import numpy as np

## I. Représentation des interactions

In [2]:
Reply = np.array([
    [1, 5, 5, 0, 3],
    [2, 0, 5, 0, 3],
    [0, 0, 0, 0, 0],
    [2, 0, 0, 4, 0],
    [0, 4, 2, 0, 0]
])

Reply

array([[1, 5, 5, 0, 3],
       [2, 0, 5, 0, 3],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 4, 0],
       [0, 4, 2, 0, 0]])

In [3]:
Retweet = np.array([
    [0, 2, 4, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 4, 3],
    [0, 2, 5, 0, 0]
])

Retweet

array([[0, 2, 4, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 4, 3],
       [0, 2, 5, 0, 0]])

In [4]:
Like = np.array([
    [2, 5, 1, 0, 3],
    [0, 0, 0, 0, 0],
    [0, 5, 0, 3, 3],
    [1, 0, 0, 4, 1],
    [0, 0, 9, 0, 0]
])

Like

array([[2, 5, 1, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 5, 0, 3, 3],
       [1, 0, 0, 4, 1],
       [0, 0, 9, 0, 0]])

In [5]:
Post = np.array([2, 5, 10, 4, 3])

Post

array([ 2,  5, 10,  4,  3])

## II. Statistiques d’engagement

In [6]:
# (01) Trouver l'utilisateur qui répond (Reply) plus que les autres
reply_out = Reply.sum(axis=1)

reply_out.argmax()

0

In [7]:
# (02) Trouver l'utilisateur qui partage (Retweet) plus que les autres
retweet_out = Retweet.sum(axis=1)

retweet_out.argmax()

3

In [8]:
# (03) Trouver les utilisateurs qui ne répondent pas (Reply) et qui ne partagent pas (Retweet)
reply_retweet_out = reply_out + retweet_out

reply_retweet_out == 0

array([False, False,  True, False, False])

In [9]:
# (04-a) Créer une matrice diagonale en utilisant la première dimention de la matrice des Likes

I = np.eye(Like.shape[0])

I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
# (04-b) Afficher le nombre des Likes que chaque utilisateur fait pour ses propres tweets

nbr_self_likes = (I * Like).sum(axis=1)

nbr_self_likes

array([2., 0., 0., 4., 0.])

In [11]:
# (05) Afficher le nombre des Likes que chaque utilisateur fait pour les tweets autre que les tien

like_out = Like.sum(axis=1)

nbr_notself_likes = like_out - nbr_self_likes

nbr_notself_likes

array([ 9.,  0., 11.,  2.,  9.])

In [12]:
# (06) Trouver les utilisateurs qui aiment leurs propres tweets plus qu'ils aiment les tweets des autres

like_more_self = nbr_notself_likes <  nbr_self_likes

like_more_self

array([False, False, False,  True, False])

In [13]:
# (07) Calculer leur nombre

like_more_self.astype(int).sum()

1

In [14]:
# (08) Afficher le nombre des interactions que chaque utilisateur a fait

reply_retweet_out + like_out

array([31, 10, 11, 19, 22])

## III. Statistiques sur les interactions

In [15]:
# (01) Afficher le max des Likes que chaque utilisateur a reçu

max_likes_in = Like.max(axis=0)

max_likes_in

array([2, 5, 9, 4, 3])

In [16]:
# (02) Trouver les utilisateurs qui ont des likes pour tous leurs tweets au moins par une personne

max_likes_in == Post

array([ True,  True, False,  True,  True])

In [17]:
# (03) calculer le nombre des arcs entrants (ayant au moins une interaction)

in_arcs = ((Reply + Retweet + Like) > 0).astype(int).sum(axis=0)

in_arcs

array([3, 3, 3, 2, 4])

In [18]:
# (04) calculer le nombre des arcs sortants (qui ont fait au moins une interaction)
out_arcs = ((Reply + Retweet + Like) > 0).astype(int).sum(axis=1)

out_arcs

array([4, 3, 3, 3, 2])

In [19]:
# (05) Trouver les neouds où le nombre des arcs entrants est égale au nombre de ceux sortants

in_more_out = in_arcs == out_arcs

in_more_out

array([False,  True,  True, False, False])

In [20]:
# (06) Afficher les Likes qu'ils ont fait entre eux

Like[:, in_more_out][in_more_out, :]

array([[0, 0],
       [5, 0]])

## Popularité

In [21]:
I1 = 1 - I

I1

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

In [27]:
# On ne s'intéresse pas par les interactions réflexives qui sont représentées par la diagonale. 

Reply_others = Reply   * I1
Retweet_self = Retweet * I
Like_others  = Like    * I1
Like_self    = Like    * I

Reply_others, Retweet_self, Like_others, Like_self

(array([[0., 5., 5., 0., 3.],
        [2., 0., 5., 0., 3.],
        [0., 0., 0., 0., 0.],
        [2., 0., 0., 0., 0.],
        [0., 4., 2., 0., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 4., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[0., 5., 1., 0., 3.],
        [0., 0., 0., 0., 0.],
        [0., 5., 0., 3., 3.],
        [1., 0., 0., 0., 1.],
        [0., 0., 9., 0., 0.]]),
 array([[2., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 4., 0.],
        [0., 0., 0., 0., 0.]]))

In [28]:
# Pour chaque interaction, 
# si le nombre des Reply reçus d'une personne est plus que celui des Likes, 
# on le multiplie par (-0.5). 

Reply_score = np.where(Reply_others > Like_others, Reply_others * (-0.5), 
                       np.where(Reply_others == Like_others, Like_self * (-0.25), 0) )

Reply_score

array([[-0.5, -0. , -2.5, -0. , -0. ],
       [-1. , -0. , -2.5, -0. , -1.5],
       [-0. ,  0. , -0. ,  0. ,  0. ],
       [-1. , -0. , -0. , -1. ,  0. ],
       [-0. , -2. ,  0. , -0. , -0. ]])

In [29]:
Retweet_score = Retweet_self * (-0.25)

Retweet_score

array([[-0., -0., -0., -0., -0.],
       [-0., -0., -0., -0., -0.],
       [-0., -0., -0., -0., -0.],
       [-0., -0., -0., -1., -0.],
       [-0., -0., -0., -0., -0.]])

In [30]:
# Pour chaque interaction, 
# si le nombre des Likes reçus d'une personne est plus que la moitié des tweets publiées, 
# on le multiplie par (1.5).

Post_moitie = (Post/2) * np.ones(Like.shape)

Like_score = np.where(Like_others > Post_moitie, Like_others * 1.5, Like_others)
Like_score

array([[ 0. ,  7.5,  1. ,  0. ,  4.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  7.5,  0. ,  4.5,  4.5],
       [ 1. ,  0. ,  0. ,  0. ,  1. ],
       [ 0. ,  0. , 13.5,  0. ,  0. ]])

In [33]:
Reply_score_avg   = Reply_score.mean(axis=0)
Retweet_score_avg = Retweet_score.mean(axis=0)
Like_score_avg    = Like_score.mean(axis=0)

Reply_score_avg, Retweet_score_avg, Like_score_avg

(array([-0.5, -0.4, -1. , -0.2, -0.3]),
 array([ 0. ,  0. ,  0. , -0.2,  0. ]),
 array([0.2, 3. , 2.9, 0.9, 2. ]))

In [34]:
Popularity = (Reply_score_avg + Retweet_score_avg + Like_score_avg)/3

Popularity

array([-0.1       ,  0.86666667,  0.63333333,  0.16666667,  0.56666667])