# Workshop : Numpy

## Représentation des interactions

In [1]:
import numpy as np

In [2]:
Reply = np.array([
    [1, 5, 5, 2, 3],
    [2, 0, 0, 0, 3],
    [0, 0, 0, 0, 0],
    [2, 0, 0, 4, 0],
    [0, 4, 2, 0, 0]
])

Reply

array([[1, 5, 5, 2, 3],
       [2, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 4, 0],
       [0, 4, 2, 0, 0]])

In [3]:
Retweet = np.array([
    [0, 2, 4, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 4, 3],
    [0, 2, 5, 0, 0]
])

Retweet

array([[0, 2, 4, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 4, 3],
       [0, 2, 5, 0, 0]])

In [4]:
Like = np.array([
    [2, 5, 1, 0, 3],
    [0, 0, 0, 0, 0],
    [0, 5, 0, 3, 3],
    [1, 0, 0, 4, 1],
    [0, 0, 9, 0, 0]
])

Like

array([[2, 5, 1, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 5, 0, 3, 3],
       [1, 0, 0, 4, 1],
       [0, 0, 9, 0, 0]])

In [6]:
Post = np.array([2, 5, 10, 4, 3])

Post

array([ 2,  5, 10,  4,  3])

## Statistiques d’engagement

In [7]:
# 1. Trouver l’utilisateur qui répond (Reply) plus que les autres.
reply_out = Reply.sum(axis=1)

reply_out.argmax()

0

In [8]:
# 2. Trouver l’utilisateur qui partage (Retweet) plus que les autres.
retweet_out = Retweet.sum(axis=1)

retweet_out.argmax()

3

In [9]:
# 3. Trouver les utilisateurs qui ne répondent pas (Reply) et qui ne partagent pas (Retweet).
reply_retweet_out = reply_out + retweet_out

reply_retweet_out == 0

array([False, False,  True, False, False])

In [10]:
# Créer une matrice diagonale en utilisant la première dimention de la matrice des Likes

I = np.eye(Like.shape[0])

I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
# 4. Afficher le nombre des Likes que chaque utilisateur a donné à ses propres tweets.

nbr_self_likes = (I * Like).sum(axis=1)

nbr_self_likes

array([2., 0., 0., 4., 0.])

In [12]:
# 5. Afficher le nombre des Likes que chaque utilisateur a donné aux tweets autre que ces propres tweets.

like_out = Like.sum(axis=1)

nbr_notself_likes = like_out - nbr_self_likes

nbr_notself_likes

array([ 9.,  0., 11.,  2.,  9.])

In [13]:
# 6. Trouver les utilisateurs qui aiment leurs propres tweets plus qu’ils aiment les tweets des autres.

like_more_self = nbr_notself_likes <  nbr_self_likes

like_more_self

array([False, False, False,  True, False])

In [14]:
# 7. Calculer leur nombre.

like_more_self.astype(int).sum()

1

In [15]:
# 8. Afficher le nombre des interactions que chaque utilisateur a fait.

reply_retweet_out + like_out

array([33,  5, 11, 19, 22])

## Statistiques sur les interactions

In [16]:
# 1. Afficher le max des Likes que chaque utilisateur a reçu (des utilisateurs autres que lui-même). 

max_likes_in_others = (Like * (1-I)).max(axis=0)

max_likes_in_others

array([1., 5., 9., 3., 3.])

In [17]:
# 1'. Afficher le max des Likes que chaque utilisateur a reçu

max_likes_in = Like.max(axis=0)

max_likes_in

array([2, 5, 9, 4, 3])

In [19]:
# 2. Trouver les utilisateurs qui ont des likes pour tous leurs tweets au moins par une personne autre qu'elle

max_likes_in_others == Post

array([False,  True, False, False,  True])

In [20]:
# 3. calculer le nombre des arcs entrants (ayant au moins une interaction)

in_arcs = ((Reply + Retweet + Like) > 0).astype(int).sum(axis=0)

in_arcs

array([3, 3, 2, 3, 4])

In [21]:
# 4. calculer le nombre des arcs sortants (qui ont fait au moins une interaction)
out_arcs = ((Reply + Retweet + Like) > 0).astype(int).sum(axis=1)

out_arcs

array([5, 2, 3, 3, 2])

In [22]:
# 5. Trouver les noeuds où le nombre des arcs entrants est égale au nombre de ceux sortants

in_eq_out = in_arcs == out_arcs

in_eq_out

array([False, False, False,  True, False])

In [25]:
# 6. Afficher les Likes qu'ils ont fait entre eux

Like[:, in_eq_out][in_eq_out, :]

array([[4]])

# Popularité

In [26]:
I1 = 1 - I

I1

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

In [27]:
# Nous ne nous intéressons pas par les interactions réflexives 

Reply_others = Reply * I1 # Reply pour les autres
Retweet_others = Retweet * I1 # Retweet pour les autres
Like_others = Like * I1 # Likes pour les atres
Like_self = Like * I # Likes pour sois-meme


Reply_others, Retweet_others, Like_others, Like_self

(array([[0., 5., 5., 2., 3.],
        [2., 0., 0., 0., 3.],
        [0., 0., 0., 0., 0.],
        [2., 0., 0., 0., 0.],
        [0., 4., 2., 0., 0.]]),
 array([[0., 2., 4., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 3.],
        [0., 2., 5., 0., 0.]]),
 array([[0., 5., 1., 0., 3.],
        [0., 0., 0., 0., 0.],
        [0., 5., 0., 3., 3.],
        [1., 0., 0., 0., 1.],
        [0., 0., 9., 0., 0.]]),
 array([[2., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 4., 0.],
        [0., 0., 0., 0., 0.]]))

In [28]:
# Score Reply 
# si le nombre des Reply reçus d’une personne est plus que celui de ces Likes, 
#   nous multiplions le nombre des Reply par (-0.5). 
# S’il est égale, nous multiplions ces propres Likes par (-0.25). 
# Sinon, il n’a aucun effet (0). 

Reply_score = np.where(Reply_others > Like_others, 
                       Reply_others * (-0.5), np.where(Reply_others == Like_others, Like_self * (-0.25), 0) )

Reply_score

array([[-0.5, -0. , -2.5, -1. , -0. ],
       [-1. , -0. , -0. , -0. , -1.5],
       [-0. ,  0. , -0. ,  0. ,  0. ],
       [-1. , -0. , -0. , -1. ,  0. ],
       [-0. , -2. ,  0. , -0. , -0. ]])

In [29]:
# Score Retweet 
# Si quelqu’un fait des Retweets à ces propres tweets, 
#  il va être sanctionné par (-0.25) pour chaque retweet.

Retweet_score = (Retweet * I) * -0.25

Retweet_score

array([[-0., -0., -0., -0., -0.],
       [-0., -0., -0., -0., -0.],
       [-0., -0., -0., -0., -0.],
       [-0., -0., -0., -1., -0.],
       [-0., -0., -0., -0., -0.]])

In [30]:
# Score Likes 
# Si le nombre des Likes reçus d’une personne est plus grand que la moitié des tweets publiées, 
#   nous le multiplions par (1.5). 
# Sinon, le score est le nombre des Likes.

Post_half = Post/2 # la moitié des postes
Post_half = np.ones(Like.shape) * Post_half # répéter les postes pour avoir une matrice
# nous pouvons utiliser np.repeat

Like_score = np.where(Like_others > Post_half, Like_others * 1.5, Like_others)

Like_score

array([[ 0. ,  7.5,  1. ,  0. ,  4.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  7.5,  0. ,  4.5,  4.5],
       [ 1. ,  0. ,  0. ,  0. ,  1. ],
       [ 0. ,  0. , 13.5,  0. ,  0. ]])