# Lab : Outils (Numpy)

In [1]:
import numpy as np

## I. Représentation des interactions

In [2]:
Reply = np.array([
    [1, 5, 5, 0, 3],
    [2, 0, 5, 0, 3],
    [0, 0, 0, 0, 0],
    [2, 0, 0, 4, 0],
    [0, 4, 2, 0, 0]
])

Reply

array([[1, 5, 5, 0, 3],
       [2, 0, 5, 0, 3],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 4, 0],
       [0, 4, 2, 0, 0]])

In [3]:
Retweet = np.array([
    [0, 2, 4, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 3],
    [0, 2, 5, 0, 0]
])

Retweet

array([[0, 2, 4, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3],
       [0, 2, 5, 0, 0]])

In [4]:
Like = np.array([
    [2, 5, 1, 0, 3],
    [0, 0, 0, 0, 0],
    [0, 5, 0, 3, 3],
    [1, 0, 0, 4, 1],
    [0, 0, 9, 0, 0]
])

Like

array([[2, 5, 1, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 5, 0, 3, 3],
       [1, 0, 0, 4, 1],
       [0, 0, 9, 0, 0]])

In [5]:
Post = np.array([2, 5, 10, 4, 3])

Post

array([ 2,  5, 10,  4,  3])

## II. Statistiques d’engagement

In [6]:
# (01) Trouver l'utilisateur qui répond (Reply) plus que les autres
reply_out = Reply.sum(axis=1)

reply_out.argmax()

0

In [7]:
# (02) Trouver l'utilisateur qui partage (Retweet) plus que les autres
retweet_out = Retweet.sum(axis=1)

retweet_out.argmax()

4

In [ ]:
# (03) Trouver les utilisateurs qui ne répondent pas (Reply) et qui ne partagent pas (Retweet)
reply_retweet_out = reply_out + retweet_out

reply_retweet_out == 0

In [ ]:
# (04-a) Créer une matrice diagonale en utilisant la première dimention de la matrice des Likes

I = np.eye(Like.shape[0])

I

In [ ]:
# (04-b) Afficher le nombre des Likes que chaque utilisateur fait pour ses propres tweets

nbr_self_likes = (I * Like).sum(axis=1)

nbr_self_likes

In [ ]:
# (05) Afficher le nombre des Likes que chaque utilisateur fait pour les tweets autre que les tien

like_out = Like.sum(axis=1)

nbr_notself_likes = like_out - nbr_self_likes

nbr_notself_likes

In [ ]:
# (06) Trouver les utilisateurs qui aiment leurs propres tweets plus qu'ils aiment les tweets des autres

like_more_self = nbr_notself_likes <  nbr_self_likes

like_more_self

In [ ]:
# (07) Calculer leur nombre

like_more_self.astype(int).sum()

In [ ]:
# (08) Afficher le nombre des interactions que chaque utilisateur a fait

reply_retweet_out + like_out

## III. Statistiques sur les interactions

In [ ]:
# (01) Afficher le max des Likes que chaque utilisateur a reçu

max_likes_in = Like.max(axis=0)

max_likes_in

In [ ]:
# (02) Trouver les utilisateurs qui ont des likes pour tous leurs tweets au moins par une personne

max_likes_in == Post

In [ ]:
# (03) calculer le nombre des arcs entrants (ayant au moins une interaction)

in_arcs = ((Reply + Retweet + Like) > 0).astype(int).sum(axis=0)

in_arcs

In [ ]:
# (04) calculer le nombre des arcs sortants (qui ont fait au moins une interaction)
out_arcs = ((Reply + Retweet + Like) > 0).astype(int).sum(axis=1)

out_arcs

In [ ]:
# (05) Trouver les neouds où le nombre des arcs entrants est égale au nombre de ceux sortants

in_more_out = in_arcs == out_arcs

in_more_out

In [ ]:
# (06) Afficher les Likes qu'ils ont fait entre eux

Like[:, in_more_out][in_more_out, :]

## Popularité

In [ ]:
I1 = 1 - I

I1

In [ ]:
# On ne s'intéresse pas par les interactions réflexives qui sont représentées par la diagonale. 

Reply2 = Reply * I1
Retweet2 = Retweet * I1
Like2 = Like * I1

Reply2, Retweet2, Like2

In [ ]:
# Pour chaque interaction, 
# si le nombre des Reply reçus d'une personne est plus que celui des Likes, 
# on le multiplie par (-0.5). 

Reply3 = np.where(Reply2 > Like2, Reply2 * (-0.5), np.where(Reply2 == Like2, 0, Reply2) )

Reply3

In [ ]:
# Pour chaque interaction, 
# si le nombre des Likes reçus d'une personne est plus que la moitié des tweets publiées, 
# on le multiplie par (1.5).

Post2 = Post/2
Post3 = np.ones(Like.shape)
Post3 = Post3 * Post2


Like3 = np.where(Like2 > Post3, Like2 * 1.5, Like2)
Like3